[package]
name = "squire_bot"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.58.0"
authors = ["TylerBloom <tylerbloom2222@gmail.com>"]

[dependencies]
#mtgjson = { git = "https://github.com/TylerBloom/mtgjson-rust-sdk", branch = "main" }
#tricebot = { git = "https://github.com/TylerBloom/tricebot-sdk", branch = "main" }
squire_core = { git = "https://github.com/MonarchDevelopment/SquireCore", branch = "main" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", features = ["framework", "standard_framework", "rustls_backend", "client", "gateway", "rustls_backend", "model"] }
dotenv = { version = "0.9" }
serde = { version = "1.0" }
serde_json = { version = "1.0.68" }
dashmap = { version = "5.0", features = ["serde"] }
rand = { version = "0.8" }
